# A skin for a terminal with neo-ansi compatible terminal palette
syntax_theme = "SolarizedDark"

[skin]
default = "ansi(7) none / ansi(7) ansi(232)"
tree = "ansi(8) none"
parent = "ansi(4) none"
file = "ansi(7) none"
directory = "ansi(4) none bold"
exe = "ansi(1) none"
link = "ansi(5) none italic"
pruning = "ansi(8) none italic"
perm__ = "ansi(7) none"
perm_r = "ansi(7) none"
perm_w = "ansi(7) none"
perm_x = "ansi(7) none"
owner = "ansi(7) none"
group = "ansi(7) none"
count = "ansi(7) none"
dates = "ansi(7) none"
sparse = "ansi(7) none"
content_extract = "ansi(8) none"
content_match = "ansi(10) none bold"
char_match = "ansi(10) none bold"
selected_line = "none ansi(243)"
file_error = "ansi(9) ansi(238)"
flag_label = "ansi(238) ansi(250) / ansi(238) ansi(244)"
flag_value = "ansi(238) ansi(250) bold / ansi(238) ansi(244)"
input = "ansi(238) ansi(250) / ansi(238) ansi(244)"
status_error = "ansi(9) none"
status_job = "ansi(5) none"
status_normal = "ansi(5) none"
status_italic = "ansi(5) none"
status_bold = "ansi(5) none"
status_code = "ansi(5) none"
status_ellipsis = "ansi(5) none"
device_id_major = "ansi(7) none"
device_id_sep = "ansi(7) none"
device_id_minor = "ansi(7) none"
git_branch = "ansi(7) none"
git_insertions = "ansi(2) none"
git_deletions = "ansi(1) none"
git_status_current = "ansi(7) none"
git_status_modified = "ansi(2) none"
git_status_new = "ansi(2) none bold"
git_status_ignored = "ansi(8) none"
git_status_conflicted = "ansi(2) none"
git_status_other = "ansi(7) none"
purpose_normal = "ansi(7) none"
purpose_italic = "ansi(7) none"
purpose_bold = "ansi(7) none bold"
purpose_ellipsis = "ansi(7) none"
scrollbar_track = "ansi(8) none  / ansi(8) none"
scrollbar_thumb = "ansi(8) none  / ansi(8) none"
help_paragraph = "ansi(7) none"
help_bold = "ansi(10) none bold"
help_italic = "ansi(15) none italic"
help_code = "ansi(3) none"
help_headers = "ansi(1) none"
help_table_border = "ansi(8) none"
preview = "ansi(7) none"
preview_title = "ansi(15) none bold"
preview_line_number = "ansi(8) none"
preview_match = "none ansi(234)"
hex_null = "ansi(14) none"
hex_ascii_graphic = "ansi(5) none"
hex_ascii_whitespace = "ansi(6) none"
hex_ascii_other = "ansi(7) none"
hex_non_ascii = "ansi(15) none"
staging_area_title = "ansi(7) none"
mode_command_mark = "ansi(7) none bold"
good_to_bad_0 = "ansi(2)"
good_to_bad_1 = "ansi(2)"
good_to_bad_2 = "ansi(2)"
good_to_bad_3 = "ansi(3)"
good_to_bad_4 = "ansi(3)"
good_to_bad_5 = "ansi(3)"
good_to_bad_6 = "ansi(3)"
good_to_bad_7 = "ansi(1)"
good_to_bad_8 = "ansi(1)"
good_to_bad_9 = "ansi(1)"
