"attribute" = "yellow"
"type" = "yellow"
"type.builtin" = "red"
#"type.enum" = "white"
#"type.enum.variant" = "white"
"constructor" = "light-blue"
"constant" = "light-red"
# "constant.builtin" = "white"
# "constant.builtin.boolean" = "white"
# "constant.character" = "white"
# "constant.character.escape" = "white"
# "constant.numeric" = "white"
# "constant.numeric.integer" = "white"
# "constant.numeric.float" = "white"
"string" = "green"
"string.regexp" = "cyan"
"string.special" = "cyan"
# "string.special.path" = "white"
# "string.special.url" = "white"
# "string.special.symbol" = "white"
"comment" = { fg = "gray", modifiers = ["dim"] }
# "comment.line" = "white"
# "comment.block" = "white"
# "comment.block.documentation" = "white"
"variable" = "white"
"variable.builtin" = "light-blue"
# "variable.parameter" = "white"
# "variable.other" = "white"
# "variable.other.member" = "white"
"label" = "white"
"punctuation" = "light-cyan"
# "punctuation.delimiter" = "white"
# "punctuation.bracket" = "white"
# "punctuation.special" = "white"
"keyword" = { fg = "magenta", modifiers = ["bold"] }
# "keyword.control" = "white"
# "keyword.control.conditional" = "white"
# "keyword.control.repeat" = "white"
# "keyword.control.import" = "white"
# "keyword.control.export" = "white"
# "keyword.control.return" = "white"
# "keyword.control.exception" = "white"
# "keyword.operator" = "white"
# "keyword.directive" = "white"
# "keyword.function" = "white"
# "keyword.storage" = "white"
# "keyword.storage.type" = "white"
# "keyword.storage.modifier" = "white"
"operator" = "blue"
"function" = "blue"
"function.builtin" = "light-blue"
# "function.method" = "white"
"function.macro" = "cyan"
"function.special" = "cyan"
"tag" = "red"
"tag.builtin" = { fg = "magenta", modifiers = ["bold"] }
"namespace" = "white"
"special" = "white"
#"markup" = "white"
"markup.heading" = { fg = "red", modifiers = [] }
"markup.heading.marker" = { fg = "light-red", modifiers = ["bold"] }
"markup.heading.1" = { fg = "red", modifiers = ["bold"] }
"markup.heading.2" = { fg = "magenta", modifiers = ["bold"] }
"markup.heading.3" = { fg = "blue", modifiers = ["bold"] }
"markup.heading.4" = { fg = "default", modifiers = ["bold"] }
"markup.heading.5" = { fg = "default", modifiers = [] }
"markup.heading.6" = { fg = "default", modifiers = [] }
"markup.list" = "light-yellow"
# "markup.list.unnumbered" = "white"
# "markup.list.numbered" = "white"
# "markup.list.checked" = "white"
# "markup.list.unchecked" = "white"
"markup.bold" = { modifiers = ["bold"] }
"markup.italic" = { modifiers = ["italic"] }
"markup.strikethrough" = { fg = "gray", modifiers = ["crossed_out"] }
"markup.link" = "green"
"markup.link.url" = { fg = "green", underline.style="line" }
"markup.link.label" = "yellow"
"markup.link.text" = "yellow"
"markup.quote" = "cyan"
"markup.raw" = "blue"
# "markup.raw.inline" = "white"
# "markup.raw.block" = "white"
